version: '3.8'

services:
  frontend:
    build:
      context: ./front/caei_training_front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=/api
    networks:
      - app-network

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASS=mouhanned2002
      - DB_NAME=caei_training
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./back/uploads:/app/uploads
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 